# -*- coding: utf-8 -*-
"""ENCRYPTION.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7VZzJ60v5P4O2P89fy4H4hOV3RI9MWG
"""

print("ENCRYPTION MACHINE READY")
h_j = {"A":"%","B":"-","C":"@","D":"#","E":"₹","F":"&","G":"£","H":"€","I":"_","J":"^","K":"[","L":"}","M":"]","N":"/:/","O":"…","P":"!","Q":"?","R":"|","S":";","T":"/","U":"=","V":"X","W":")","X":"(","Y":"A","Z":"Q"}
r_s = {"A":"Z","B":"S","C":"N","D":"X","E":"Q","F":"A","G":"F","H":"J","I":"Y","J":"X","K":"R","L":"!","M":"V","N":"C","O":"L","P":"H","Q":"G","R":"K","S":"N","T":"D","U":"T","V":"&","W":"%","X":"M","Y":"@","Z":"B"}
code1 = 12791
code2 = 14891
def encryption(data,key):
  decrypted = ""
  if key == code1:
    encryption_mode = h_j
  elif key == code2:
    encryption_mode = r_s
  else:
    print('ERROR')
    exit()
  for alphabet in data:
    alphabet = alphabet.upper()
    if alphabet == " ":
      decrypted += " "
    elif alphabet == "," or alphabet == ".":
      decrypted += alphabet
    else:
      decrypted += str(encryption_mode.get(alphabet))
  print("DECRYPTED")
  print(decrypted)
  return
inputted = list(input(""))
print(" ")
key = int(input("KEY "))
print(" ")
encryption(inputted,key)